name: Build Release From Tag

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract version from tag
        id: version
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          echo "Tag: TAG"
          echo "VERSION=$TAG" >> $GITHUB_ENV


      - name: Read latest changelog
        id: changelog
        shell: bash
        run: |
          echo "changelog<<EOF" >> "$GITHUB_OUTPUT"
          .github/scripts/read-changelog.sh >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"      

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: ${{ inputs.disable_gradle_cache && '' || 'gradle' }}

      - name: Decode keystore
        env:
          KEYSTORE_FILE_B64: ${{ secrets.KEYSTORE_FILE_B64 }}
        run: echo "$KEYSTORE_FILE_B64" | base64 -d > my-release-key.jks

      - name: Export signing env
        run: |
          {
            echo "KEYSTORE_FILE=$PWD/my-release-key.jks"
            echo "KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}"
            echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}"
            echo "KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}"
          } >> $GITHUB_ENV

      - name: Build Release APK
        run: ./gradlew assembleStableRelease assembleBetaDebuggableRelease --parallel --no-daemon --no-build-cache -x lint

      - name: Rename APK
        run: |
          NAME="DragonLauncher-${{ env.VERSION }}.apk"
          mv app/build/outputs/apk/stable/release/app-stable-release.apk "$NAME"

          DEBUG="DragonLauncher-${{ env.VERSION }}-debuggable.apk"
          mv app/build/outputs/apk/beta/debuggableRelease/app-beta-debuggableRelease.apk "$DEBUG"
          
          MAPPINGS_MIN="Mappings-${{ env.VERSION }}.txt"
          MAPPINGS_DEBUG="Mappings-${{ env.VERSION }}-debuggable.txt"
          
          [ -f "app/build/outputs/mapping/stableRelease/mapping.txt" ] && cp app/build/outputs/mapping/stableRelease/mapping.txt "$MAPPINGS_MIN"
          [ -f "app/build/outputs/mapping/debuggableRelease/mapping.txt" ] && cp app/build/outputs/mapping/debuggableRelease/mapping.txt "$MAPPINGS_DEBUG"
          
          echo "Debug file: $DEBUG"
          echo "Release file: $NAME"
          echo "Mappings files: $MAPPINGS_MIN, $MAPPINGS_DEBUG"
        
          {
            echo "APK_DEBUG=$DEBUG"
            echo "APK=$NAME"
            echo "$MAPPINGS_MIN=$MAPPINGS_MIN"
            echo "$MAPPINGS_DEBUG=$MAPPINGS_DEBUG"
          } >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          name: ${{ env.VERSION }}
          files: |
            ${{ env.APK }}
            ${{ env.APK_DEBUG }}
            ${{ env.MAPPINGS_MIN }}
            ${{ env.MAPPINGS_DEBUG }}
          body: |
            ${{ steps.changelog.outputs.changelog }}

            ### Debuggable version
            If you encounter bugs or crash, you can install the debuggable version of the app, and check for logs using your computer via ***adb***
            Here's some [help](https://developer.android.com/tools/logcat)

            ## ⚠️ Play Protect Warning
            Due to Android restrictions, disable Play Protect during installation to avoid Dragon being blocked.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
